---

- name: Ensure directory for user exists
  file:
    path: /var/www
    state: directory
    mode: 0755

- name: Ensure directory for user exists
  file:
    path: /var/www/tvbeers
    state: directory
    mode: 0755

- name: Set up user tvbeers
  user:
    name: tvbeers
    home: /var/www/tvbeers
  #become: true

- name: Add epel-release repo
  yum:
    name: epel-release
    state: present

- name: Ensure packages are installed
  yum:
    name:
      - nginx
      - python36
      - python-virtualenv

- name: Template nginx vhost
  template:
    src: "{{ tvbeers_nginx_vhost_src }}"
    dest: "/etc/nginx/conf.d/tvbeers-nginx-vhost.conf" 
    owner: root
    group: root
    mode: 0644
  register: nginx-vhost
  notify: restart nginx

- name: Verify nginx config
  command: nginx -t
  changed_when: false
  register: nginx-config

- name: Ensure nginx is running
  service:
    name: nginx
    state: started


